const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Accessories',
    price: 36867.60,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Phone',
    price: 245784.00,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Accessories',
    price: 380961.10,
    countInStock: 5,
    rating: 3.5,
    numReviews: 4,
  },
  {
    _id: '4',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Console',
    price: 163851.90,
    countInStock: 11,
    rating: 5,
    numReviews: 2,
  },
  {
    _id: '5',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Accessories',
    price: 20477.90,
    countInStock: 0,
    rating: 3.5,
    numReviews: 6,
  },
  {
    _id: '6',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Accessories',
    price: 12285.10,
    countInStock: 0,
    rating: 4,
    numReviews: 5,
  },
  {
    _id: '7',
    name: 'Apple Watch Sport 42mm',
    image: '/images/watch.png',
    description:
      `System on a chip: Apple S1,
      Storage: 8 GB,
      Initial operating system: watchOS 1.0,
      Display: 42 mm: 24.34 30.42 mm; 38.96 mm (1.534 in) diagonally, 312390 pixels, 326 PPI,
      Battery: 246mAh`,
    brand: 'Apple',
    category: 'Watch',
    price: 150000.00,
    countInStock: 0,
    rating: 3.5,
    numReviews: 1,
  },
  {
    _id: '8',
    name: 'Apple MacBook Pro - 13" - 512GB - 16GB',
    image: '/images/Mac.png',
    description:
      `Tenth-generation quad-core Intel Core i5 processor 2020, Brilliant Retina display with True Tone technology,Backlit Magic Keyboard, Touch Bar and Touch ID, Intel Iris Plus Graphics
      Ultrafast SSD,
      Four Thunderbolt 3 (USB-C) ports,
      Up to 10 hours of battery life,
      802.11ac Wi-Fi,
      Force Touch trackpad`,
    brand: 'Amazon',
    category: 'Laptop',
    price: 899999.00,
    countInStock: 2,
    rating: 4.5,
    numReviews: 8,
  },
]

export default products
